services:
  web:
    build: .
    container_name: help50_web
    depends_on:
      - mysql
    environment:
      APPLICATION_ENV: dev
      APP_URL: http://localhost:8080/
      HELP50_PASSWORD: crimson
      MYSQL_DATABASE: help50
      MYSQL_HOST: mysql
      MYSQL_PASSWORD: crimson
      MYSQL_USERNAME: root
    links:
      - mysql
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www
  mysql:
    container_name: help50_mysql
    image: mysql
    environment:
      MYSQL_DATABASE: help50
      MYSQL_ROOT_PASSWORD: crimson
version: "2"
